### ISSUE TITLE
Format on Save leaves the file unsaved after changes

### ISSUE THREAD

**Issue by asik** [deviousasti/fsharp-formatting-for-vs#11]
**Current behavior:**
When saving a code file, if the file is reformatted, then it ends up having unsaved changes, and the user must save a second time to commit these formatting changes.

**Expected behavior:**
You should only ever have to save once.

Seen in version 0.7.1
Visual Studio Enterprise 2019 Version 16.8.4

**Comment by deviousasti** [comment]
Thank you for reporting this, @asik.
I agree with how it should behave - I originally didn't implement it because there might be a save-format-save-format loop, but that's been taken care of. I've published a new version, please update and try it out.

The issue got auto-closed by mentioning it in the commit. 
If you still have any issues, feel free to re-open this.

Have a good day!

**Comment by bddckr** [comment]
Is there a way to make this behavior configurable perhaps? 🙏 The old behavior was really handy for me:

Fantomas has a few bugs I keep running into:
* fsprojects/fantomas#1388: Forces me to keep peeking at the scrollbar and see if VS shows me any ping-ponging formatting on each save. I then scroll down to each change and have a look at each change to invoke the save once more until it's formatted the way I'd like the file to stay at that point.
* [Various issues that end up removing comments in the code](https://github.com/fsprojects/fantomas/issues?q=is%3Aissue+is%3Aopen++comment): I often don't want to remove the code I commented out - I'm just doing some changes to test something quickly, without other logic running.

I've turned off formatting on save in the options for now as I no longer have any ability to keep going back to the "correct" state of the file after this change.

E.g. with format on save turned on when I hit save it formats the code and removes the commented code accidentally:
* Before this change: Just hit Ctrl+Z once to get the file back to the saved state, which is the state I typed, but not the formatted state. This way I can bring back anything Fantomas accidentally did wrong.
* After this change: I can still undo the formatting changes, but I can't save it as that would format+save again. I have to turn off formatting on save.

---

While I'm here: Thanks for this extension and all the hard work on it!!!

**Comment by deviousasti** [comment]
A real-life case of xkcd/1172!
![xkcd](https://imgs.xkcd.com/comics/workflow.png)

@bddckr 
These days I use `Ctrl-K, Ctrl-D`, (keybind for formatting in VS).
Earlier I used exactly the workflow you described - I used to review the changes Fantomas made before hard-saving, because my comments or attributes would get eaten.

I'll make it configurable.

**Comment by bddckr** [comment]
Yeah I honestly gotta say formatting specifically triggering formatting is totally fine with me... If only I would stop forgetting to do it before raising PRs! I've yet to make Fantomas part of our CI 😅

Thanks for looking into making it an option, much appreciated!

**Comment by deviousasti** [comment]
Just published 0.7.3 which features an option to not commit changes on save.
Have a nice weekend!

Feel free to reopen or file another issue if you have any more problems.

**Comment by bddckr** [comment]
Thanks! I see what you did there in the Performance section 😆❤️
