### ISSUE TITLE
Q: Use nuget instead of submodule?

### ISSUE THREAD

**Issue by nojaf** [deviousasti/fsharp-formatting-for-vs#5]
Hey @deviousasti, 

Is there any reason that you use a submodule instead of the [Fantomas nuget](https://www.nuget.org/packages/Fantomas/4.0.0-beta-001) package?
Could I persuade you to use the version on NuGet? That way (in theory) the same experience can be guaranteed when you switch between vscode and VS.

**Comment by deviousasti** [comment]
I'd initially started off with the nuget package while prototyping. 

Being able to step into the source has been invaluable for development, and if a particular fix in main branch is needed, I can ship it without waiting for a nuget release, which seems to vary in frequency from 3 days to a week.

VS code is more isolated because, afaik, they use the fantomas-cli process, while for VS, it's in-process - I need to make sure that Fantomas is built using the correct .Net framework version and FCS for Visual Studio. 

That was my reasoning.

**Comment by nojaf** [comment]
Thanks for explaining this. It makes sense, giving you are targeting VS and in-process.
Time will tell how confusing this will be for users that use both editors.
If nobody reports it, it is not a problem 🙈.
