### ISSUE TITLE
Formatting stopped working in VS2019

### ISSUE THREAD

**Issue by johannesvp** [deviousasti/fsharp-formatting-for-vs#7]
The extension probably automatically updated to version 0.4.5.1 and stopped working. 
I am using Microsoft Visual Studio Professional 2019, Version 16.7.3

The message in the statusbar:
Could not format: Could not load type 'InterpolatedString' from assembly 'FSharp.Compiler.Service, version 36.0.3.0, etc'

**Comment by deviousasti** [comment]
Thank you for reporting this.
May I ask if you're using any other F# extensions at the moment?

Since [0.4.3](https://github.com/deviousasti/fsharp-formatting-for-vs/blob/master/Release%20Notes.md#043) we've moved over to FCS 37, so I'm wondering if another extension in VS is causing FCS 36 to be loaded.

**Comment by johannesvp** [comment]
I removed 'F# Lint' and now it works fine. 
I noticed you are creator of FSharpLint as well, maybe you can have a look into the linter?

![image](https://user-images.githubusercontent.com/61790945/93425758-eb174e00-f8ba-11ea-8579-853adfee52d3.png)

**Comment by deviousasti** [comment]
Thanks for confirming.
I'll try to release an update tonight.

**Comment by deviousasti** [comment]
I've released new versions of both.
Could you please update?

**Comment by johannesvp** [comment]
Updated and both formatting and lint work fine now. 
Thanks
